"""
Anki Add-on: Anki Script Manager

Please do not edit this file unless you know what you are doing.

Copyright: (c) 2019-2020 Henrik Giesel <https://github.com/hgiesel>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from .src import setup
setup()
