"""
Anki Add-on: Anki Script Manager

Please do not edit this file unless you know what you are doing.

Copyright: (c) 2019 Henrik Giesel <https://github.com/hgiesel>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from os import path
import json

from aqt import mw

from .src.main import setup_models_dialog

if mw.addonManager.addonName(path.dirname(__file__)) != 'Asset Manager':
    dir_path = path.dirname(path.realpath(__file__))

    with open(path.join(dir_path, 'manifest.json')) as f:
        config_data = {}

        try:
            with open(path.join(dir_path, 'meta.json')) as f_old:
                config_data = json.load(f_old)['config']

        except FileNotFoundError:
            pass

        meta = json.load(f)
        meta.update({
            'config': config_data,
        })

        mw.addonManager.writeAddonMeta(dir_path, meta)

setup_models_dialog()
